### ISSUE TITLE
Doesn't escape quotes properly

### ISSUE THREAD

**Issue by markwalet** [rmariuzzo/laravel-localization-loader#3]
When I use ` 'more' => 'Meer pagina\'s',` in my php file, the compilation crashes. When I remove the `\'` the compiling succeeds.

**Comment by rmariuzzo** [comment]
Hey @markwalet! Thanks for taking your time on reporting this. I will create a broken test with your details and bring a fix.

**Comment by markwalet** [comment]
Thanks for the quick response!

**Comment by rmariuzzo** [comment]
Hey @markwalet! I have added the test, however it worked flawlessly with both JSON and PHP input. Can you post the error you are receiving? Plus any other relevant details.

**Comment by markwalet** [comment]
Huh, that's weird. I can't reproduce the bug as well. 
I'll close the issue. Letting you know when it crashes again. Thanks for your help!

**Comment by rmariuzzo** [comment]
Let me know if you encounter any issue.
