### ISSUE TITLE
Problem with building complex translations

### ISSUE THREAD

**Issue by chilio** [rmariuzzo/laravel-localization-loader#6]
I have a problem with building complex translations.
Let's assume I want to use multiline translations and some html inside...
So for test purposes  I have this declaration in one of my lang files:
```
 'test'      => <<<'TEXT'
Test </br>
Test
TEXT
,
```
@rmariuzzo any idea on how to solve this?

**Comment by rmariuzzo** [comment]
@chilio what about using multiline string in PHP as follow:

```php
 'test'      => "TEXT
Test </br>
Test
TEXT"
,
```

Note where the opening and closing `"` are.

**Comment by chilio** [comment]
@rmariuzzo I use vsch/laravel-translation-manager and each time I put multiline string in translation  it uses `<<<TEXT`  in translation file, that's why it doesn't play well together.
Any other ideas? I will ask them also...

**Comment by chilio** [comment]
@rmariuzzo this is solved for now, but wouldn't you think of integrating all php arrays types in your package to cover this scenario?

**Comment by rmariuzzo** [comment]
@chilio indeed we should cover it. We can take a look together and see how to implement it properly.

**Comment by chilio** [comment]
@rmariuzzo great to hear that, but as said before I'm pretty new to javascript modules, therefore I could help more on testing or php side.

For the moment it seems that your php parsers should be able to follow [HEREDOC and NOWDOC convention](http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc) to make it work.

**Side note:** In php 7 and upwards there is no limitation in strings on 64-bit systems (which I believe are the most used cases for latest laravel installattions, unfortunately for sure not for all), but that is the main reason I could safely **turn on** `USE_QUOTES` and **turn off** `USE_HEREDOC` in vsch package (php 7.2 64bit used here).
Therefore I think it might get really rare usage. 

So my conclusion is, if you can provide this functionality with small effort, please do....

Anyway let me know, if you decided to make this package more cross versions compatible and especially if you have any new build to test that out....
